spring:
  application:
    name: member-service
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/ua_member
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE # 3.x ???? ???? DEFAULT(UTC) ? ???? NORMALIZE(JVM ?? ??) ???.
        format_sql: true
        use_sql_comments: true
        show_sql: true # ? ??? SQL ?? ??? ?????.
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG # Hibernate SQL ??? DEBUG ??? ??
    org.hibernate.type: TRACE # Hibernate ?? ??? TRACE ??? ??

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false # 서비스 목록 가져오기