server:
  port: 10001

spring:
  application:
    name: member-service
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:~/ua_member
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE # 3.x ???? ???? DEFAULT(UTC) ? ???? NORMALIZE(JVM ?? ??) ???.
        format_sql: true
        use_sql_comments: true
        show_sql: true # ? ??? SQL ?? ??? ?????.
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG # Hibernate SQL ??? DEBUG ??? ??
    org.hibernate.type: TRACE # Hibernate ?? ??? TRACE ??? ??

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true # 서비스 목록 가져오기

jwt:
  secretKey : e9013edcc71fee14ac0b407e65e2f187b99e0365d9a31cf13ea2680b79e134718cd9777a7eea4b3a21aa16018e53a2c687843451a72c99ca3ffc05f4f0a21b4d